<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BB84.Extensions" Version="5.0.916" />
    <PackageVersion Include="BB84.SourceGenerators" Version="2.4.903" />
    <PackageVersion Include="Hexa.NET.DirectXTex" Version="2.0.4" />
    <PackageVersion Include="Moq" Version="4.21.0" />
    <PackageVersion Include="MSTest" Version="4.4.1" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.55.0" />
  </ItemGroup>
</Project>