# configuration file for dotnet-releaser
[msbuild]
project = "DDS.Tools.sln"
configuration = "Release"
[github]
user = "BoBoBaSs84"
repo = "DDS.Tools"
# Create zip files only for Windows platforms
[[pack]]
rid = ["win-x64"]
kinds = ["zip"]
[[pack]]
rid = ["win-arm", "win-arm64"]
kinds = ["zip"]
publish = false
# Default targets for Linux/Ubuntu Debian compatible distro with debian and tar packages
[[pack]]
rid = ["linux-x64", "linux-arm", "linux-arm64"]
kinds = ["deb", "tar"]
publish = false
# Default targets for Linux/Redhat compatible distro with rpm and tar packages
[[pack]]
rid = ["rhel-x64"]
kinds = ["rpm", "tar"]
publish = false
# Default targets for macOS, only tar files for this platform
[[pack]]
rid = ["osx-x64", "osx-arm64"]
kinds = ["tar"]
publish = false
[nuget]
publish = false
