//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("https://github.com/BoBoBaSs84")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2023 BoBoBaSs84")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("This is a simple DDS and PNG tool set.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2023.9.19.1109")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2023.9.19.1109-Development")]
[assembly: System.Reflection.AssemblyProductAttribute("DDS.Tools")]
[assembly: System.Reflection.AssemblyTitleAttribute("DDS2PNG")]
[assembly: System.Reflection.AssemblyVersionAttribute("2023.9.19.1109")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/BoBoBaSs84/DDS.Tools")]
[assembly: System.Resources.NeutralResourcesLanguageAttribute("en-US")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo(@"DDS2PNGTests, PublicKey=0024000004800000940000000602000000240000525341310004000001000100b184b023cf3895017dfa742a6e86fa8587b7099565277e0e89f2caad95c2b50c2716edc64c2c01740f1659ffd5f5682baacccb80622c034e3942c9704eb47f51cfd6b1907189f270331d68f57ff0492e7a0244cd03afe40f0eb4c7da314a88ec9cfbd284f4485d4a909c0bce387bfd14345b194c4494395ec16e7e8c4ca940f5")]

// Generated by the MSBuild WriteCodeFragment class.

