//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Shared.LibraryTests")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2023.9.19.1092")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2023.9.19.1092-Development")]
[assembly: System.Reflection.AssemblyProductAttribute("Shared.LibraryTests")]
[assembly: System.Reflection.AssemblyTitleAttribute("Shared.LibraryTests")]
[assembly: System.Reflection.AssemblyVersionAttribute("2023.9.19.1092")]

// Generated by the MSBuild WriteCodeFragment class.

