name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup
      uses: actions/setup-dotnet@v4

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration release --verbosity minimal

    - name: Test
      run: dotnet test --no-build --configuration release --verbosity minimal
